import React, { useState, useEffect, useMemo } from "react";
import { MONAI_TASKS, MonaiTask, getRecommendedMonaiTasks } from "../../constants/monai-tasks";
import { monaiService } from "../../services/monai-service";

export interface MonaiTabProps {
  selectedSeriesUid?: string | null;
  selectedSeriesMetadata?: {
    modality?: string;
    bodyPartExamined?: string;
    seriesDescription?: string;
    contrastBolusAgent?: string;
    instanceCount?: number;
  };
  segmentingSeriesUid?: string | null;
  onRunMonai?: (seriesUid: string, task: string, scoreThreshold?: number) => void;
  loadedSegs?: Array<{ seriesUid: string; seriesDescription: string; modality: string }>;
  segDataMap?: Record<string, any>;
  onSelectSegSeries?: (imageSeriesUid: string, segSeriesUid: string) => void;
  onDeleteSegSeries?: (segSeriesUid: string) => void;
  activeSegSeriesUid?: string | null;
}

const MONAI_CATEGORIES = [
  { id: "all", label: "All Models" },
  { id: "chest", label: "Chest & Lungs (GGN)" },
  { id: "abdomen", label: "Abdomen" },
  { id: "oncology", label: "Oncology" },
  { id: "neuro_mri", label: "MRI & Neuro" },
  { id: "musculoskeletal", label: "Spine & Bones" },
];

export const MonaiTab: React.FC<MonaiTabProps> = ({
  selectedSeriesUid,
  selectedSeriesMetadata,
  segmentingSeriesUid,
  onRunMonai,
  loadedSegs = [],
  segDataMap = {},
  onSelectSegSeries,
  onDeleteSegSeries,
  activeSegSeriesUid,
}) => {
  const [selectedCategory, setSelectedCategory] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [activeMode, setActiveMode] = useState<"recommended" | "explore">("recommended");
  const [runningTaskId, setRunningTaskId] = useState<string | null>(null);
  const [installedTasks, setInstalledTasks] = useState<string[]>([]);
  const [selectedCardTaskId, setSelectedCardTaskId] = useState<string | null>(null);
  const [expandedStructures, setExpandedStructures] = useState<Set<string>>(new Set());

  const isSegmenting = Boolean(segmentingSeriesUid);

  useEffect(() => {
    monaiService.getInstalledTasks().then(setInstalledTasks);
  }, [segmentingSeriesUid, loadedSegs.length]);

  const toggleExpand = (taskId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setExpandedStructures((prev) => {
      const next = new Set(prev);
      if (next.has(taskId)) next.delete(taskId);
      else next.add(taskId);
      return next;
    });
  };

  const cleanQuery = searchQuery.trim().toLowerCase();

  // Recommendation engine
  const recommendedTasks = useMemo(() => {
    return getRecommendedMonaiTasks(selectedSeriesMetadata);
  }, [selectedSeriesMetadata]);

  // Filtered task lists
  const filterTask = (task: MonaiTask) => {
    if (selectedCategory !== "all" && task.category !== selectedCategory) {
      return false;
    }
    if (!cleanQuery) return true;

    const nameMatch = task.name.toLowerCase().includes(cleanQuery);
    const descMatch = task.description.toLowerCase().includes(cleanQuery);
    const structMatch = task.structures.some((s) => s.toLowerCase().includes(cleanQuery));
    const catMatch = task.categoryLabel.toLowerCase().includes(cleanQuery);

    return nameMatch || descMatch || structMatch || catMatch;
  };

  const filteredRecommended = useMemo(
    () => recommendedTasks.filter(filterTask),
    [recommendedTasks, selectedCategory, cleanQuery]
  );

  const filteredAll = useMemo(
    () => MONAI_TASKS.filter(filterTask),
    [selectedCategory, cleanQuery]
  );

  const findCompletedSeg = (taskId: string) => {
    return loadedSegs.find((s) => {
      const desc = (s.seriesDescription || "").toLowerCase();
      const parsed = segDataMap[s.seriesUid];
      const label = (parsed?.contentLabel || "").toLowerCase();
      const contentDesc = (parsed?.contentDescription || "").toLowerCase();
      const manufacturer = (parsed?.manufacturer || "").toLowerCase();

      // Must be strictly generated by MONAI pipeline
      const isMonaiSeg =
        desc.startsWith("monai:") ||
        desc.includes("monai") ||
        label.startsWith("monai_") ||
        label.includes("monai") ||
        contentDesc.includes("monai") ||
        manufacturer.includes("monai");

      if (!isMonaiSeg) return false;

      const taskClean = taskId.replace(/_/g, "").toLowerCase();
      return (
        desc.includes(taskClean) ||
        label.includes(taskClean) ||
        contentDesc.includes(taskClean)
      );
    });
  };

  const handleRun = (task: MonaiTask) => {
    if (!selectedSeriesUid || isSegmenting) return;
    setRunningTaskId(task.id);
    onRunMonai?.(selectedSeriesUid, task.id, 0.20);
  };

  const modality = selectedSeriesMetadata?.modality || "CT";
  const bodyPart = selectedSeriesMetadata?.bodyPartExamined || "Chest / Abdomen";
  const contrast = selectedSeriesMetadata?.contrastBolusAgent ? "Contrast-Enhanced" : "Non-Contrast";

  const renderIcon = (taskId: string) => {
    if (taskId.includes("lung") || taskId.includes("covid")) return "🫁";
    if (taskId.includes("brain")) return "🧠";
    if (taskId.includes("liver") || taskId.includes("spleen") || taskId.includes("pancreas")) return "🩺";
    if (taskId.includes("colon") || taskId.includes("prostate")) return "🔬";
    if (taskId.includes("vertebrae")) return "🦴";
    return "⚡";
  };

  const renderCard = (task: MonaiTask, isRecommended = false) => {
    const completedSeg = findCompletedSeg(task.id);
    const isSegActive = Boolean(
      completedSeg &&
        (selectedCardTaskId === task.id ||
          (activeSegSeriesUid && completedSeg.seriesUid === activeSegSeriesUid))
    );
    const isThisRunning = isSegmenting && runningTaskId === task.id;
    const isExpanded = expandedStructures.has(task.id);

    const visibleStructures = isExpanded ? task.structures : task.structures.slice(0, 3);
    const remainingCount = task.structures.length - 3;

    return (
      <div
        key={task.id}
        className={`totalseg-task-card monai-card ${isRecommended ? "recommended" : ""} ${
          completedSeg ? "is-completed is-clickable" : ""
        } ${isSegActive ? "is-active" : ""}`}
        onClick={
          completedSeg
            ? () => {
                if (selectedSeriesUid) {
                  setSelectedCardTaskId(task.id);
                  onSelectSegSeries?.(selectedSeriesUid, completedSeg.seriesUid);
                }
              }
            : undefined
        }
        style={{ cursor: completedSeg ? "pointer" : "default" }}
      >
        {/* Header */}
        <div className="totalseg-task-header-section">
          <div className="totalseg-task-icon-container monai-icon-box">
            <span style={{ fontSize: "1.3rem" }}>{renderIcon(task.id)}</span>
          </div>
          <div className="totalseg-task-header-content">
            <span className="totalseg-task-name">{task.name}</span>

            <div className="totalseg-badges-and-tags-row">
              {completedSeg && (
                <span className="totalseg-completed-badge">✓ Completed</span>
              )}
              {isRecommended && !completedSeg && (
                <span className="totalseg-match-badge">Matched</span>
              )}
              {installedTasks.includes(task.id) && (
                <span className="totalseg-downloaded-badge" title="Model cached locally">
                  ⚡ Downloaded
                </span>
              )}
              <span className="monai-type-badge">{task.modelType}</span>
              <span className="totalseg-task-tag">{task.modality}</span>

              {visibleStructures.map((s) => {
                const isMatched = Boolean(cleanQuery && s.toLowerCase().includes(cleanQuery));
                return (
                  <span
                    key={s}
                    className={`totalseg-structure-tag ${isMatched ? "matched" : ""}`}
                  >
                    {s}
                  </span>
                );
              })}

              {remainingCount > 0 && (
                <button
                  type="button"
                  className={`totalseg-structure-tag more ${isExpanded ? "active" : ""}`}
                  onClick={(e) => toggleExpand(task.id, e)}
                >
                  {isExpanded ? "show less" : `+${remainingCount} more`}
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Description */}
        <span className="totalseg-task-desc">{task.description}</span>

        {/* Footer */}
        <div className="totalseg-task-footer">
          {completedSeg ? (
            <div className="totalseg-completed-action-group">
              <button
                className="totalseg-rerun-btn"
                disabled={isSegmenting}
                onClick={(e) => {
                  e.stopPropagation();
                  handleRun(task);
                }}
                title={`Re-run ${task.name}`}
              >
                {isThisRunning ? (
                  <span className="loading-spinner small" />
                ) : (
                  <span>🔄</span>
                )}
              </button>

              {onDeleteSegSeries && (
                <button
                  className="totalseg-delete-btn"
                  disabled={isSegmenting}
                  onClick={(e) => {
                    e.stopPropagation();
                    if (window.confirm(`Delete ${task.name} segmentation?`)) {
                      onDeleteSegSeries(completedSeg.seriesUid);
                    }
                  }}
                  title={`Delete ${task.name} segmentation`}
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="3 6 5 6 21 6" />
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                    <line x1="10" y1="11" x2="10" y2="17" />
                    <line x1="14" y1="11" x2="14" y2="17" />
                  </svg>
                </button>
              )}
            </div>
          ) : (
            <button
              className="totalseg-run-btn monai-run-btn"
              disabled={isSegmenting}
              onClick={() => handleRun(task)}
              title={`Run ${task.name} with MONAI AI`}
            >
              {isThisRunning ? (
                <span className="loading-spinner small" />
              ) : (
                <>
                  <span>⚡</span>
                  <span>Inference</span>
                </>
              )}
            </button>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="totalseg-tab-view monai-tab-view">
      {/* Header & Scan Context */}
      <div className="totalseg-sticky-header">
        <div className="totalseg-scan-context-card">
          <div className="totalseg-scan-context-header">
            <div className="totalseg-scan-context-left">
              <span className="totalseg-scan-badge monai-badge">{modality} • MONAI</span>
              <span className="totalseg-scan-bodypart">{bodyPart}</span>
              <span className="totalseg-scan-contrast">{contrast}</span>
            </div>
            <span className="monai-model-count-pill">{MONAI_TASKS.length} Models</span>
          </div>
        </div>

        {/* Search */}
        <div className="totalseg-search-bar-wrap">
          <div className="totalseg-search-box">
            <svg
              className="totalseg-search-icon"
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <circle cx="11" cy="11" r="8" />
              <line x1="21" y1="21" x2="16.65" y2="16.65" />
            </svg>
            <input
              type="text"
              className="totalseg-search-input"
              placeholder="Search MONAI models, GGN nodules, organs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            {searchQuery && (
              <button
                type="button"
                className="totalseg-search-clear-btn"
                onClick={() => setSearchQuery("")}
              >
                ✕
              </button>
            )}
          </div>
        </div>

        {/* Navigation Tabs (Recommended vs Explore) */}
        <div className="totalseg-tabs-bar">
          <div className="totalseg-mode-tabs">
            <button
              type="button"
              className={`totalseg-mode-tab ${activeMode === "recommended" ? "active recommended" : ""}`}
              onClick={() => setActiveMode("recommended")}
              title="Recommended Models"
              aria-label="Recommended Models"
            >
              <svg
                width="15"
                height="15"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M9 18h6" />
                <path d="M10 22h4" />
                <path d="M15.09 14c.18-.98.65-1.74 1.41-2.5A4.65 4.65 0 0 0 18 8 6 6 0 0 0 6 8c0 1 .23 2.23 1.5 3.5A4.61 4.61 0 0 1 8.91 14" />
              </svg>
            </button>

            <button
              type="button"
              className={`totalseg-mode-tab ${activeMode === "explore" ? "active explore" : ""}`}
              onClick={() => setActiveMode("explore")}
              title="Explore All Models"
              aria-label="Explore All Models"
            >
              <svg
                width="15"
                height="15"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <polygon
                  points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"
                  fill="currentColor"
                  fillOpacity="0.25"
                />
              </svg>
            </button>
          </div>

          <div className="totalseg-tabs-bar-meta">
            <span className="totalseg-tabs-count">
              {activeMode === "recommended"
                ? `${filteredRecommended.length} recommended`
                : `${filteredAll.length} models`}
            </span>
          </div>
        </div>

        {/* Category Filter Pills (Horizontal Scrolling) */}
        <div className="totalseg-category-pills-wrap">
          <div className="totalseg-category-pills">
            {MONAI_CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                type="button"
                className={`totalseg-category-pill ${selectedCategory === cat.id ? "active" : ""}`}
                onClick={() => setSelectedCategory(cat.id)}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="totalseg-task-list" style={{ padding: "8px 12px 24px 12px" }}>
        {activeMode === "recommended" ? (
          filteredRecommended.length === 0 ? (
            <div className="totalseg-empty-filter-state">
              <span style={{ fontSize: "1.4rem" }}>🔍</span>
              <span className="totalseg-empty-filter-title">No matching recommended models</span>
              <span className="totalseg-empty-filter-desc">
                Switch to "Explore All" or change category filter to see all {MONAI_TASKS.length} MONAI models.
              </span>
              <button
                type="button"
                className="totalseg-clear-filters-btn"
                onClick={() => {
                  setSelectedCategory("all");
                  setSearchQuery("");
                  setActiveMode("explore");
                }}
              >
                Explore All Models
              </button>
            </div>
          ) : (
            filteredRecommended.map((task) => renderCard(task, true))
          )
        ) : filteredAll.length === 0 ? (
          <div className="totalseg-empty-filter-state">
            <span style={{ fontSize: "1.4rem" }}>🔍</span>
            <span className="totalseg-empty-filter-title">No models found</span>
            <span className="totalseg-empty-filter-desc">Try clearing search filters.</span>
            <button
              type="button"
              className="totalseg-clear-filters-btn"
              onClick={() => {
                setSelectedCategory("all");
                setSearchQuery("");
              }}
            >
              Reset Filters
            </button>
          </div>
        ) : (
          filteredAll.map((task) => renderCard(task, false))
        )}
      </div>
    </div>
  );
};
